favicon: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🥷</text></svg>"
title: Blades
gtm_id: GTM-WNHMRQZ
brand: <big><a href="/" class="dark-auto"><i>🥷&nbsp;</i>Blades</a></big>
header_links:
  - url: https://github.com/anydigital/awesome-blades
    title: <i>🕶️</i>
  - url: https://github.com/anydigital/blades
    title: <i class="fa-brands fa-github"></i>
footer_links:
  - url: https://github.com/anydigital/blades
    title: |-
      <img style="vertical-align: -0.125em" src="https://img.shields.io/github/stars/anydigital/blades?label=🥷&logo=%20" />
